<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFrameworks>net8.0;net10.0</TargetFrameworks>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <Version>1.1.0</Version>
    <PackageIcon>logo.png</PackageIcon>
    <PackageReadmeFile>README.md</PackageReadmeFile>
    <PublishRepositoryUrl>true</PublishRepositoryUrl>
    <RepositoryUrl>https://github.com/3-Degrees-Technologies/Iban</RepositoryUrl>
    <RepositoryType>git</RepositoryType>
  </PropertyGroup>

  <ItemGroup>
    <None Include="logo.png" Pack="true" PackagePath="/" />
    <None Include="..\..\README.md" Pack="true" PackagePath="/" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="IbanNet" Version="6.1.0" />
    <PackageReference Include="IbanNet.Extensions.Bban" Version="3.0.0" />
    <PackageReference Include="ModulusChecker.NetCore" Version="2.5.0" />
  </ItemGroup>

</Project>
