<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="IbanNet" Version="5.19.0" />
    <PackageReference Include="IbanNet.Extensions.Bban" Version="1.0.0" />
    <PackageReference Include="IbanNet.FluentValidation" Version="5.19.0" />
  </ItemGroup>
</Project>
